name: Deploy App

on:
  push:
    branches:
      - dev
      - main
  workflow_run:
    workflows: ["Create github release and tag"]
    types:
      - completed
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_run' && github.ref == 'refs/heads/main' && 'production' || github.event_name == 'push' && github.ref == 'refs/heads/main' && 'staging' || 'dev'}}
    steps:
      - name: Print Tag
        run: |
          echo "Tag (ref): ${{ github.ref }}"
          echo "Tag (ref_name): ${{ github.ref_name }}"
          echo "Start with ref: ${{ startsWith(github.ref, 'refs/tags/') }}"
          echo "Event name: ${{ github.event_name }}"
      - name: Check if tag push event
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Tag push event detected!"
      - name: Dump event payload
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Event payload:"
          echo "$EVENT_PAYLOAD"
      - name: Dump environment name
        run: |
          echo "Environment: ${{ env.CURRENT_ENV }}" # production, staging, dev
