name: Deploy App

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Create github release and tag"]
    types:
      - completed
jobs:
  set-environment:
    name: Set environment
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set_env.outputs.environment }}
    steps:
      - name: Set environment
        id: set_env
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "environment=stage" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
        shell: bash
  build_and_deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Proceed only if Workflow A succeeded
    name: Build Docker image, push to ECR, and deploy to ECS
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - set-environment
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
      - name: Set ECS environment variables
        id: set_vars
        run: |
          ENVIRONMENT=${{ needs.set-environment.outputs.environment }}
          echo "ECS_CLUSTER=sample-app-${ENVIRONMENT}-ecs-cluster" >> $GITHUB_ENV
      - name: Print Tag
        run: |
          echo "Tag (ref): ${{ github.ref }}"
          echo "Tag (ref_name): ${{ github.ref_name }}"
          echo "Event name: ${{ github.event_name }}"
      - name: Set branch variable
        id: set-branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_run" ]; then
            echo "BRANCH=main" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_name }}" == "main" ]; then
            echo "BRANCH=main" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref_name }}" == "dev" ]; then
            echo "BRANCH=dev" >> $GITHUB_ENV
          else
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
      - name: Check if tag push event
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Tag push event detected!"
      - name: Dump event payload
        env:
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: |
          echo "Event payload:"
          echo "$EVENT_PAYLOAD"
      - name: Dump environment name
        run: |
          echo "Environment: ${{ needs.set-environment.outputs.environment }}" # prod, stage, dev
