name: Test Tag Trigger

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Tag
        run: | 
          echo "Tag (ref): ${{ github.ref }}"
          echo "Tag (ref_name): ${{ github.ref_name }}"
          echo "Start with ref: ${{ startsWith(github.ref, 'refs/tags/') }}"
